sudo: required
language: python
dist: trusty
python:
  - "2.7"
after_success:
  - codecov
virtualenv:
  system_site_packages: true
install:
  - echo "127.0.0.1 localhost" | sudo tee /etc/hosts
  - echo "127.0.0.1 ca.example.lan ca" | sudo tee -a /etc/hosts
  - echo "127.0.0.1 vpn.koodur.lan" | sudo tee -a /etc/hosts
  - sudo pip install -r requirements.txt
  - sudo pip install codecov pytest-cov
  - sudo pip install --editable .
script:
  - sudo useradd adminbot -G sudo -p '$1$PBkf5waA$n9EV6WJ7PS6lyGWkgeTPf1'
  - sudo useradd userbot -G users -p '$1$PBkf5waA$n9EV6WJ7PS6lyGWkgeTPf1'
  - sudo adduser --system --no-create-home --group certidude
  - sudo py.test -s --cov-report xml --cov=certidude tests/
cache:
  directories:
    - $HOME/.cache/pip
addons:
  hostname: ca
  apt:
    packages:
    - python-configparser
