sudo: required
language: python
dist: trusty
python:
  - "2.7"
after_success:
  - codecov
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-configparser python-setuptools
  - pip install codecov pytest-cov
install:
  - pip install -r requirements.txt
  - pip install --editable .
script:
  - py.test && py.test --cov-report xml --cov=certidude tests/
cache:
  directories:
    - $HOME/.cache/pip
