sudo: required
language: python
dist: trusty
python:
  - "3.4"
after_success:
  - codecov
virtualenv:
  system_site_packages: true
install:
  - sudo mkdir -p /etc/systemd/system # Until Travis is stuck with 14.04
  - sudo -E pip install -r requirements.txt
  - sudo -E pip install codecov pytest-cov requests-kerberos
  - sudo -E pip install -e .
script:
  - sudo find /home/ -type d -exec chmod 755 {} \; # Allow certidude serve to read templates
  - sudo chmod 777 . # Allow forked processes to write .coverage files
  - sudo -E coverage run --parallel-mode --source certidude -m py.test tests
  - sudo -E coverage combine
  - sudo -E coverage report
  - sudo -E coverage xml -i
cache:
  directories:
    - $HOME/.cache/pip
addons:
  hostname: ca
  apt:
    packages:
    - software-properties-common
    - python3-click
    - python3-mysql.connector
    - python3-pyxattr
