sudo: required
language: python
dist: trusty
python:
  - "2.7"
after_success:
  - codecov
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
  - pip install --editable .
  - pip install codecov pytest-cov click ipaddress humanize falcon simplepam
script:
  - sudo useradd adminbot -G sudo -p '$1$PBkf5waA$n9EV6WJ7PS6lyGWkgeTPf1'
  - sudo useradd userbot -G users -p '$1$PBkf5waA$n9EV6WJ7PS6lyGWkgeTPf1'
  - sudo usermod -a -G shadow $USER
  - sudo -E su $USER -c 'py.test --cov-report xml --cov=certidude tests/'
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
    - python-xattr
    - python-setproctitle
    - python-markdown
    - python-jinja2
    - python-configparser
    - python-pyasn1
    - python-openssl
