sudo: required
language: python
dist: trusty
python:
  - "3.4"
after_success:
  - codecov
virtualenv:
  system_site_packages: true
install:
  - sudo mkdir -p /etc/systemd/system # Until Travis is stuck with 14.04
  - sudo pip3 install -r requirements.txt
  - sudo pip3 install codecov pytest-cov requests-kerberos
  - sudo pip3 install -e .
script:
  - sudo find /home/ -type d -exec chmod 755 {} \; # Allow certidude serve to read templates
  - sudo chmod 777 . # Allow forked processes to write .coverage files
  - sudo coverage run --parallel-mode --source certidude -m py.test tests
  - sudo coverage combine
  - sudo coverage report
  - sudo coverage xml -i
cache:
  directories:
    - $HOME/.cache/pip
addons:
  hostname: ca
  apt:
    packages:
    - software-properties-common
