sudo: false
language: python
dist: trusty
python:
  - "2.7"
after_success:
  - codecov
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
  - pip install --editable .
script:
  - py.test && py.test --cov-report xml --cov=certidude tests/
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
    - python-configparser
    - python-setuptools
    - python-ldap
    - python-mysql.connector
    - python-pysqlite2
    - python-cffi
    - cython
#  - pip install codecov pytest-cov
